// Complete planetary data for the Solar System simulator
// All distances in AU, radii in km, periods in Earth days, tilts in degrees

export const PLANET_DATA = {
  sun: {
    name: 'Sun',
    nameKo: '\ud0dc\uc591',
    emoji: '☀️',
    factsKo: [
      '태양은 스스로 빛나는 별이에요.',
      '태양이 있어서 지구가 따뜻해요.',
      '절대 맨눈으로 오래 보면 안 돼요!',
    ],
    sizeComparisonKo: '태양 지름은 지구 109개를 나란히 놓은 만큼이에요!',
    radius: 696350,
    displayRadius: 50,
    color: 0xffdd44,
    emissive: 0xffaa00,
    rotationPeriod: 609.12,
    axialTilt: 7.25,
  },
  mercury: {
    name: 'Mercury',
    nameKo: '\uc218\uc131',
    emoji: '🌑',
    factsKo: [
      '태양과 가장 가까운 행성이에요.',
      '낮에는 아주 뜨겁고 밤에는 아주 추워요.',
      '1년이 88일밖에 안 돼요.',
    ],
    sizeComparisonKo: '수성 2개 반을 나란히 놓으면 지구 폭이에요!',
    radius: 2440,
    displayRadius: 4,
    distance: 0.387,
    distanceDisplay: 80,
    orbitalPeriod: 87.97,
    rotationPeriod: 1407.6,
    axialTilt: 0.034,
    eccentricity: 0.2056,
    inclination: 7.0,
    color: 0xb5b5b5,
    moons: 0,
  },
  venus: {
    name: 'Venus',
    nameKo: '\uae08\uc131',
    emoji: '🟡',
    factsKo: [
      '구름에 싸여 있어서 하얗게 보여요.',
      '태양계에서 가장 뜨거운 행성이에요.',
      '저녁 하늘에서 가장 밝게 빛나요.',
    ],
    sizeComparisonKo: '금성은 지구와 크기가 거의 같은 쌍둥이예요!',
    radius: 6052,
    displayRadius: 7,
    distance: 0.723,
    distanceDisplay: 150,
    orbitalPeriod: 224.7,
    rotationPeriod: -5832.5,
    axialTilt: 177.4,
    eccentricity: 0.0068,
    inclination: 3.39,
    color: 0xe8cda0,
    moons: 0,
  },
  earth: {
    name: 'Earth',
    nameKo: '\uc9c0\uad6c',
    emoji: '🌍',
    factsKo: [
      '우리가 사는 곳이에요.',
      '물이 많아서 파랗게 보여요.',
      '하루에 한 바퀴 스스로 돌아요.',
    ],
    sizeComparisonKo: '지구는 달보다 4배쯤 커요!',
    radius: 6378,
    displayRadius: 8,
    distance: 1.0,
    distanceDisplay: 200,
    orbitalPeriod: 365.25,
    rotationPeriod: 23.934,
    axialTilt: 23.44,
    eccentricity: 0.0167,
    inclination: 0.0,
    color: 0x4488ff,
    moons: 1,
  },
  mars: {
    name: 'Mars',
    nameKo: '\ud654\uc131',
    emoji: '🔴',
    factsKo: [
      '붉은 먼지로 덮여 있어서 빨갛게 보여요.',
      '태양계에서 가장 큰 화산이 있어요.',
      '로봇 탐사차가 화성을 달리고 있어요.',
    ],
    sizeComparisonKo: '화성은 지구의 절반 크기예요!',
    radius: 3396,
    displayRadius: 5,
    distance: 1.524,
    distanceDisplay: 300,
    orbitalPeriod: 687.0,
    rotationPeriod: 24.623,
    axialTilt: 25.19,
    eccentricity: 0.0934,
    inclination: 1.85,
    color: 0xcc6633,
    moons: 2,
  },
  jupiter: {
    name: 'Jupiter',
    nameKo: '\ubaa9\uc131',
    emoji: '🟠',
    factsKo: [
      '태양계에서 가장 큰 행성이에요.',
      '커다란 빨간 점은 아주 큰 폭풍이에요.',
      '위성을 아주 많이 가지고 있어요.',
    ],
    sizeComparisonKo: '지구 11개를 나란히 놓으면 목성 폭!',
    radius: 71492,
    displayRadius: 28,
    distance: 5.203,
    distanceDisplay: 450,
    orbitalPeriod: 4331,
    rotationPeriod: 9.925,
    axialTilt: 3.13,
    eccentricity: 0.0489,
    inclination: 1.3,
    color: 0xc8a55a,
    moons: 95,
  },
  saturn: {
    name: 'Saturn',
    nameKo: '\ud1a0\uc131',
    emoji: '🪐',
    factsKo: [
      '커다랗고 아름다운 고리를 두르고 있어요.',
      '고리는 얼음 조각으로 만들어졌어요.',
      '물에 넣으면 둥둥 뜰 만큼 가벼워요.',
    ],
    sizeComparisonKo: '지구 9개를 나란히 놓으면 토성 폭이에요!',
    radius: 60268,
    displayRadius: 24,
    distance: 9.537,
    distanceDisplay: 600,
    orbitalPeriod: 10747,
    rotationPeriod: 10.656,
    axialTilt: 26.73,
    eccentricity: 0.0565,
    inclination: 2.49,
    color: 0xe8d088,
    moons: 146,
    hasRings: true,
    ringInner: 66900,
    ringOuter: 140000,
  },
  uranus: {
    name: 'Uranus',
    nameKo: '\ucc9c\uc655\uc131',
    emoji: '🧊',
    factsKo: [
      '옆으로 누워서 데굴데굴 굴러가요.',
      '아주 차갑고 푸른 행성이에요.',
      '여기서 1년은 지구의 84년이에요.',
    ],
    sizeComparisonKo: '지구 4개를 나란히 놓으면 천왕성 폭이에요!',
    radius: 25559,
    displayRadius: 14,
    distance: 19.19,
    distanceDisplay: 730,
    orbitalPeriod: 30589,
    rotationPeriod: -17.24,
    axialTilt: 97.77,
    eccentricity: 0.0457,
    inclination: 0.77,
    color: 0x88ccdd,
    moons: 28,
  },
  neptune: {
    name: 'Neptune',
    nameKo: '\ud574\uc655\uc131',
    emoji: '🔵',
    factsKo: [
      '태양에서 가장 멀리 있는 행성이에요.',
      '바다처럼 짙은 파란색이에요.',
      '바람이 아주 빠르게 부는 곳이에요.',
    ],
    sizeComparisonKo: '지구 4개를 나란히 놓으면 해왕성 폭이에요!',
    radius: 24764,
    displayRadius: 13,
    distance: 30.07,
    distanceDisplay: 850,
    orbitalPeriod: 59800,
    rotationPeriod: 16.11,
    axialTilt: 28.32,
    eccentricity: 0.0113,
    inclination: 1.77,
    color: 0x4466ee,
    moons: 16,
  },
  // IAU dwarf planets (F1). category:'dwarf' drives UI classification and the
  // "Dwarf Planets" sidebar section. Textures do not ship yet — PlanetFactory
  // renders them with a flat-color fallback until art is dropped at TEXTURE_MAP.
  // distanceDisplay follows the existing symbolic scale: Ceres in the belt
  // (Mars 300 < 400 < Jupiter 450), the four TNOs beyond Neptune (850).
  ceres: {
    name: 'Ceres',
    nameKo: '세레스',
    emoji: '🪨',
    factsKo: [
      '화성과 목성 사이에 있는 왜소행성이에요.',
      '가장 먼저 발견된 왜소행성이에요.',
      '땅속에 얼음이 숨어 있어요.',
    ],
    sizeComparisonKo: '세레스 4개를 나란히 놓으면 달 폭이에요!',
    category: 'dwarf',
    radius: 473,
    displayRadius: 3,
    distance: 2.77,
    distanceDisplay: 400,
    orbitalPeriod: 1681.6,
    rotationPeriod: 9.07,
    axialTilt: 4,
    eccentricity: 0.0785,
    inclination: 10.59,
    color: 0x8c8377,
    moons: 0,
    discoveryYear: 1801,
  },
  pluto: {
    name: 'Pluto',
    nameKo: '명왕성',
    emoji: '🤍',
    factsKo: [
      '아주 멀고 추운 작은 왜소행성이에요.',
      '하트 모양 무늬가 있어요.',
      '명왕성의 1년은 지구의 248년이에요.',
    ],
    sizeComparisonKo: '명왕성은 달보다 작아요!',
    category: 'dwarf',
    radius: 1188,
    displayRadius: 3,
    distance: 39.48,
    distanceDisplay: 950,
    orbitalPeriod: 90560,
    rotationPeriod: -153.29,
    axialTilt: 122.53,
    eccentricity: 0.2488,
    inclination: 17.16,
    color: 0xd9c8a9,
    moons: 5,
    discoveryYear: 1930,
  },
  haumea: {
    name: 'Haumea',
    nameKo: '하우메아',
    emoji: '🥚',
    factsKo: [
      '달걀처럼 길쭉한 왜소행성이에요.',
      '아주 빠르게 팽이처럼 돌아요.',
      '작은 위성 두 개가 함께 돌아요.',
    ],
    sizeComparisonKo: '하우메아 2개를 나란히 놓으면 달 폭이에요!',
    category: 'dwarf',
    radius: 816,
    displayRadius: 2.6,
    distance: 43.13,
    distanceDisplay: 1000,
    orbitalPeriod: 103774,
    rotationPeriod: 3.92,
    axialTilt: 0,
    eccentricity: 0.195,
    inclination: 28.21,
    color: 0xe8e8e8,
    moons: 2,
    discoveryYear: 2004,
  },
  makemake: {
    name: 'Makemake',
    nameKo: '마케마케',
    emoji: '🟤',
    factsKo: [
      '아주 멀고 어두운 왜소행성이에요.',
      '붉은 갈색빛을 띠고 있어요.',
      '작은 위성 하나가 함께 돌아요.',
    ],
    sizeComparisonKo: '마케마케 2개 반을 나란히 놓으면 달 폭이에요!',
    category: 'dwarf',
    radius: 715,
    displayRadius: 2.6,
    distance: 45.79,
    distanceDisplay: 1050,
    orbitalPeriod: 111845,
    rotationPeriod: 22.83,
    axialTilt: 0,
    eccentricity: 0.159,
    inclination: 28.98,
    color: 0xb5651d,
    moons: 1,
    discoveryYear: 2005,
  },
  eris: {
    name: 'Eris',
    nameKo: '에리스',
    emoji: '❄️',
    factsKo: [
      '태양계에서 가장 멀리 있는 왜소행성이에요.',
      '얼음으로 덮여서 아주 반짝여요.',
      '여기서 1년은 지구의 558년이에요.',
    ],
    sizeComparisonKo: '에리스는 명왕성과 크기가 거의 같아요!',
    category: 'dwarf',
    radius: 1163,
    displayRadius: 3,
    distance: 67.78,
    distanceDisplay: 1150,
    orbitalPeriod: 203830,
    rotationPeriod: 25.9,
    axialTilt: 78,
    eccentricity: 0.4407,
    inclination: 44.04,
    color: 0xd8d8d0,
    moons: 1,
    discoveryYear: 2005,
  },
  // Halley's Comet (SPEC-EVENTS-001 REQ-EVT-101). The only comet in the sim.
  //
  // It lives in PLANET_DATA rather than its own export because it is a
  // Keplerian orbiter like everything else here: PlanetFactory's create /
  // orbit-line / per-frame-position loops all read this map, so the whole mount
  // is free. STAR_DATA is separate precisely because stars are NOT orbiters
  // (azimuth/elevation placement, no period). category:'comet' marks it for the
  // UI the same way category:'dwarf' marks the five above.
  //
  // DISPLAY SCALING — two numbers are scaled, both deliberately:
  //
  //   a: real 17.8 AU -> 700 display units, putting it on the same symbolic
  //      scale as every other body here (Mercury 80 ... Eris 1150). The real
  //      eccentricity is kept, so the shape falls out of it: perihelion
  //      q = a(1-e) = 23.1 dives well inside Mercury's 80, qualitatively
  //      matching real Halley's sub-Venus perihelion, and aphelion
  //      Q = a(1+e) = 1376.9 reaches beyond Eris's 1150, matching its real
  //      beyond-Neptune aphelion. That dive and retreat is the whole reason to
  //      draw this body.
  //
  //   T: real 76 years -> 7.6 simulation years (2775.9 days). Every other body
  //      keeps its real period; Halley alone is divided by 10, because at the
  //      real period a child never sees a perihelion pass at kid-typical
  //      simulation speeds — the pass would be off-screen behind hours of
  //      waiting. The cost is that Halley's phase relative to the planets is
  //      not physical. Accepted: the dive is the lesson, the phase is not.
  halley: {
    name: "Halley's Comet",
    nameKo: '핼리 혜성',
    emoji: '☄️',
    factsKo: [
      '76년에 한 번 지구 곁으로 찾아와요.',
      '태양에 가까워지면 긴 꼬리가 자라나요.',
      '꼬리는 언제나 태양 반대쪽으로 뻗어요.',
    ],
    sizeComparisonKo: '핼리 혜성의 얼음덩어리는 커다란 산만 해요!',
    category: 'comet',
    radius: 5.5,
    displayRadius: 2,
    distance: 17.8,
    distanceDisplay: 700,
    orbitalPeriod: 2775.9,
    rotationPeriod: 52.8,
    axialTilt: 0,
    eccentricity: 0.967,
    inclination: 162.3,
    // Orbit-line resolution override. generateOrbitPath samples uniformly in
    // true anomaly, which at e=0.967 puts its widest chords at the aphelion
    // apex — exactly where the ellipse is sharpest (curvature radius
    // a(1-e^2) = 45 units). The shared 128 default cuts that tip flat by ~10
    // display units, five nucleus diameters of visible facet; 512 brings it
    // under 1 unit and is still one LineLoop draw call. Comet-only: no other
    // body is eccentric enough to need it.
    orbitSegments: 512,
    color: 0xcfe6f0,
  },
};

// @MX:NOTE: [AUTO] The belts get their own map rather than joining PLANET_DATA or
// STAR_DATA because both of those are mesh registries: PlanetFactory builds a
// sphere for every entry in each, and every sphere it builds lands in
// `planetFactory.planets`, which is exactly the set InteractionManager raycasts.
// A belt entry in either map would therefore grow a phantom sphere AND re-open
// the picking path that REQ-EVT-203 closes. BELT_DATA is info-only: the geometry
// lives in Belts.js as one InstancedMesh, and only the list, the strip and the
// InfoPanel read this.
// @MX:SPEC: [AUTO] SPEC-EVENTS-001 REQ-EVT-203, REQ-EVT-205
export const BELT_DATA = {
  asteroidBelt: {
    name: 'Asteroid Belt',
    nameKo: '소행성대',
    emoji: '🪨',
    factsKo: [
      '화성과 목성 사이에 있는 돌멩이 밭이에요.',
      '작은 바위들이 아주 많이 모여 돌고 있어요.',
      '가장 큰 세레스는 왜소행성이 되었어요.',
    ],
    sizeComparisonKo: '가장 큰 돌은 우리나라만 하고, 작은 건 자갈만 해요!',
    category: 'belt',
    // Real main-belt span in AU, shown as a range because a band has no single
    // distance. The display-unit band (320-430) lives in Belts.js, which owns
    // the geometry; this is the number the InfoPanel reads out to a child.
    distance: '2.2 ~ 3.2',
    color: 0x8b7d6b,
  },
  kuiperBelt: {
    name: 'Kuiper Belt',
    nameKo: '카이퍼 벨트',
    emoji: '🧊',
    factsKo: [
      '해왕성보다 더 먼 바깥쪽 얼음 나라예요.',
      '명왕성도 카이퍼 벨트에 살고 있어요.',
      '혜성들이 태어나는 고향이기도 해요.',
    ],
    sizeComparisonKo: '소행성대보다 훨씬 넓고, 얼음덩어리로 가득해요!',
    category: 'belt',
    distance: '30 ~ 50',
    color: 0x9fb8c8,
  },
};

export const MOON_DATA = {
  earth: [
    {
      key: 'moon',
      name: 'Moon',
      nameKo: '\ub2ec',
      emoji: '🌕',
      factsKo: [
        '밤하늘에서 가장 밝게 보여요.',
        '달에는 공기가 없어요.',
        '사람이 직접 가 본 유일한 다른 세계예요.',
      ],
      sizeComparisonKo: '달 4개를 나란히 놓으면 지구 폭이에요!',
      radius: 1737.4,
      displayRadius: 3,
      distanceFromParent: 384400,
      distanceDisplay: 15,
      orbitalPeriod: 27.32,
      rotationPeriod: 655.7,
      axialTilt: 1.54,
      eccentricity: 0.0549,
      color: 0xaaaaaa,
    },
  ],
  mars: [
    {
      key: 'phobos',
      name: 'Phobos',
      nameKo: '\ud3ec\ubcf4\uc2a4',
      emoji: '🥔',
      factsKo: [
        '감자처럼 울퉁불퉁하게 생겼어요.',
        '화성 둘레를 하루에 세 번이나 돌아요.',
        '화성의 두 위성 중 큰 쪽이에요.',
      ],
      sizeComparisonKo: '포보스 150개를 나란히 놓아야 달 폭이에요!',
      radius: 11.267,
      displayRadius: 1.5,
      distanceFromParent: 9376,
      distanceDisplay: 10,
      orbitalPeriod: 0.319,
      rotationPeriod: 7.66,
      axialTilt: 0,
      eccentricity: 0.0151,
      color: 0x8a7d6b,
    },
    {
      key: 'deimos',
      name: 'Deimos',
      nameKo: '\ub370\uc774\ubaa8\uc2a4',
      emoji: '🌰',
      factsKo: [
        '화성의 두 위성 중 작은 쪽이에요.',
        '아주 작아서 별처럼 보여요.',
        '화성 둘레를 30시간마다 한 바퀴 돌아요.',
      ],
      sizeComparisonKo: '데이모스 280개를 나란히 놓아야 달 폭이에요!',
      radius: 6.2,
      displayRadius: 1.2,
      distanceFromParent: 23463,
      distanceDisplay: 14,
      orbitalPeriod: 1.263,
      rotationPeriod: 30.312,
      axialTilt: 0,
      eccentricity: 0.00033,
      color: 0x9b8e7e,
    },
  ],
  jupiter: [
    {
      key: 'io',
      name: 'Io',
      nameKo: '\uc774\uc624',
      emoji: '🌋',
      factsKo: [
        '화산이 펑펑 터지는 목성의 위성이에요.',
        '노랗고 알록달록한 모습이에요.',
        '이틀이 안 걸려 목성을 한 바퀴 돌아요.',
      ],
      sizeComparisonKo: '이오는 우리 달과 크기가 거의 같아요!',
      radius: 1821.6,
      displayRadius: 2.5,
      distanceFromParent: 421700,
      distanceDisplay: 40,
      orbitalPeriod: 1.769,
      rotationPeriod: 42.456,
      axialTilt: 0.04,
      eccentricity: 0.0041,
      color: 0xddcc55,
    },
    {
      key: 'europa',
      name: 'Europa',
      nameKo: '\uc720\ub85c\ud30c',
      emoji: '🌊',
      factsKo: [
        '얼음 껍질 아래에 바다가 숨어 있어요.',
        '표면에 금이 쫙쫙 그어져 있어요.',
        '얼음이 많아서 하얗게 반짝여요.',
      ],
      sizeComparisonKo: '유로파는 우리 달보다 조금 작아요!',
      radius: 1560.8,
      displayRadius: 2.3,
      distanceFromParent: 671034,
      distanceDisplay: 48,
      orbitalPeriod: 3.551,
      rotationPeriod: 85.228,
      axialTilt: 0.1,
      eccentricity: 0.009,
      color: 0xc8b89a,
    },
    {
      key: 'ganymede',
      name: 'Ganymede',
      nameKo: '\uac00\ub2c8\uba54\ub370',
      emoji: '🥇',
      factsKo: [
        '태양계에서 가장 큰 위성이에요.',
        '얼음과 바위로 이루어져 있어요.',
        '스스로 자석 힘을 가진 위성이에요.',
      ],
      sizeComparisonKo: '가니메데는 행성인 수성보다도 커요!',
      radius: 2634.1,
      displayRadius: 3,
      distanceFromParent: 1070412,
      distanceDisplay: 56,
      orbitalPeriod: 7.155,
      rotationPeriod: 171.709,
      axialTilt: 0.33,
      eccentricity: 0.0013,
      color: 0x9a8a7a,
    },
    {
      key: 'callisto',
      name: 'Callisto',
      nameKo: '\uce7c\ub9ac\uc2a4\ud1a0',
      emoji: '🌚',
      factsKo: [
        '구덩이가 아주 많은 목성의 위성이에요.',
        '아주 오래된 얼굴을 가지고 있어요.',
        '얼음과 바위가 섞여 있어요.',
      ],
      sizeComparisonKo: '칼리스토는 수성과 크기가 거의 같아요!',
      radius: 2410.3,
      displayRadius: 2.9,
      distanceFromParent: 1882700,
      distanceDisplay: 64,
      orbitalPeriod: 16.689,
      rotationPeriod: 400.536,
      axialTilt: 0,
      eccentricity: 0.0074,
      color: 0x6e6258,
    },
  ],
  // @MX:NOTE: [AUTO] Saturn's 7 hydrostatic moons are ordered by real orbital
  // distance (Mimas -> Iapetus); distanceDisplay must stay strictly increasing
  // with a non-overlapping gap so no two moons collide at Saturn's default zoom.
  saturn: [
    {
      key: 'mimas',
      name: 'Mimas',
      nameKo: '\ubbf8\ub9c8\uc2a4',
      radius: 198.2,
      displayRadius: 1.3,
      distanceFromParent: 185539,
      distanceDisplay: 34,
      orbitalPeriod: 0.942,
      rotationPeriod: 22.608,
      axialTilt: 0,
      eccentricity: 0.0196,
      color: 0xc8c8c8,
    },
    {
      key: 'enceladus',
      name: 'Enceladus',
      nameKo: '\uc5d4\uc140\ub77c\ub450\uc2a4',
      emoji: '⛲',
      factsKo: [
        '얼음 물줄기를 하늘로 뿜어내요.',
        '온통 하얀 눈으로 덮여 있어요.',
        '얼음 아래에 바다가 숨어 있어요.',
      ],
      sizeComparisonKo: '엔셀라두스 7개를 나란히 놓으면 달 폭이에요!',
      radius: 252.1,
      displayRadius: 1.5,
      distanceFromParent: 237948,
      distanceDisplay: 40,
      orbitalPeriod: 1.37,
      rotationPeriod: 32.885,
      axialTilt: 0,
      eccentricity: 0.0047,
      color: 0xeeeeff,
    },
    {
      key: 'tethys',
      name: 'Tethys',
      nameKo: '\ud14c\ud2f0\uc2a4',
      radius: 531.1,
      displayRadius: 1.8,
      distanceFromParent: 294619,
      distanceDisplay: 46,
      orbitalPeriod: 1.888,
      rotationPeriod: 45.307,
      axialTilt: 0,
      eccentricity: 0.0001,
      color: 0xd8d8d8,
    },
    {
      key: 'dione',
      name: 'Dione',
      nameKo: '\ub514\uc624\ub124',
      radius: 561.4,
      displayRadius: 1.8,
      distanceFromParent: 377396,
      distanceDisplay: 52,
      orbitalPeriod: 2.737,
      rotationPeriod: 65.686,
      axialTilt: 0,
      eccentricity: 0.0022,
      color: 0xcccccc,
    },
    {
      key: 'rhea',
      name: 'Rhea',
      nameKo: '\ub808\uc544',
      radius: 763.8,
      displayRadius: 2,
      distanceFromParent: 527108,
      distanceDisplay: 60,
      orbitalPeriod: 4.518,
      rotationPeriod: 108.42,
      axialTilt: 0.345,
      eccentricity: 0.0012,
      color: 0xbbbbcc,
    },
    {
      key: 'titan',
      name: 'Titan',
      nameKo: '\ud0c0\uc774\ud0c4',
      emoji: '🍊',
      factsKo: [
        '두꺼운 공기에 싸인 토성의 위성이에요.',
        '강과 호수가 있는 신기한 곳이에요.',
        '주황색 안개에 덮여 있어요.',
      ],
      sizeComparisonKo: '타이탄은 행성인 수성보다도 커요!',
      radius: 2574.7,
      displayRadius: 3,
      distanceFromParent: 1221870,
      distanceDisplay: 72,
      orbitalPeriod: 15.945,
      rotationPeriod: 382.68,
      axialTilt: 0.3,
      eccentricity: 0.0288,
      color: 0xd4a050,
    },
    {
      key: 'iapetus',
      name: 'Iapetus',
      nameKo: '\uc774\uc544\ud398\ud22c\uc2a4',
      radius: 734.5,
      displayRadius: 2,
      distanceFromParent: 3560820,
      distanceDisplay: 88,
      orbitalPeriod: 79.322,
      rotationPeriod: 1903.7,
      axialTilt: 0,
      eccentricity: 0.0286,
      color: 0x7a6a5a,
    },
  ],
  pluto: [
    {
      key: 'charon',
      name: 'Charon',
      nameKo: '\uce74\ub860',
      emoji: '🌗',
      factsKo: [
        '명왕성과 서로 마주 보며 함께 돌아요.',
        '명왕성의 가장 큰 위성이에요.',
        '북쪽에 붉은 모자 같은 무늬가 있어요.',
      ],
      sizeComparisonKo: '카론은 명왕성의 절반만 한 크기예요!',
      radius: 606,
      displayRadius: 1.8,
      distanceFromParent: 19591,
      distanceDisplay: 8,
      orbitalPeriod: 6.387,
      rotationPeriod: 153.29,
      axialTilt: 0,
      eccentricity: 0.0022,
      color: 0x9b8e7e,
    },
  ],
  uranus: [
    {
      key: 'titania',
      name: 'Titania',
      nameKo: '\ud2f0\ud0c0\ub2c8\uc544',
      radius: 788.4,
      displayRadius: 2,
      distanceFromParent: 435910,
      distanceDisplay: 25,
      orbitalPeriod: 8.706,
      rotationPeriod: 208.94,
      axialTilt: 0,
      eccentricity: 0.0011,
      color: 0xb0a0a0,
    },
    {
      key: 'oberon',
      name: 'Oberon',
      nameKo: '\uc624\ubca0\ub860',
      radius: 761.4,
      displayRadius: 1.8,
      distanceFromParent: 583519,
      distanceDisplay: 30,
      orbitalPeriod: 13.463,
      rotationPeriod: 323.118,
      axialTilt: 0,
      eccentricity: 0.0014,
      color: 0xa09898,
    },
    {
      key: 'miranda',
      name: 'Miranda',
      nameKo: '\ubbf8\ub780\ub2e4',
      radius: 235.8,
      displayRadius: 1.5,
      distanceFromParent: 129390,
      distanceDisplay: 20,
      orbitalPeriod: 1.413,
      rotationPeriod: 33.923,
      axialTilt: 4.34,
      eccentricity: 0.0013,
      color: 0xc0b8b0,
    },
  ],
  neptune: [
    {
      key: 'triton',
      name: 'Triton',
      nameKo: '\ud2b8\ub9ac\ud1a4',
      emoji: '🌫️',
      factsKo: [
        '해왕성 둘레를 거꾸로 도는 위성이에요.',
        '차가운 얼음 물줄기를 뿜어내요.',
        '태양계에서 가장 추운 곳 중 하나예요.',
      ],
      sizeComparisonKo: '트리톤은 명왕성보다 조금 더 커요!',
      radius: 1353.4,
      displayRadius: 2.5,
      distanceFromParent: 354759,
      distanceDisplay: 25,
      orbitalPeriod: 5.877,
      rotationPeriod: 141.043,
      axialTilt: 156.885,
      eccentricity: 0.000016,
      color: 0xb8c8d0,
      retrograde: true,
    },
    {
      key: 'proteus',
      name: 'Proteus',
      nameKo: '\ud504\ub85c\ud14c\uc6b0\uc2a4',
      radius: 210,
      displayRadius: 1.5,
      distanceFromParent: 117647,
      distanceDisplay: 20,
      orbitalPeriod: 1.122,
      rotationPeriod: 26.928,
      axialTilt: 0,
      eccentricity: 0.00053,
      color: 0x888899,
    },
    {
      key: 'nereid',
      name: 'Nereid',
      nameKo: '\ub124\ub808\uc774\ub4dc',
      radius: 170,
      displayRadius: 1.3,
      distanceFromParent: 5513400,
      distanceDisplay: 35,
      orbitalPeriod: 360.14,
      rotationPeriod: 11.594,
      axialTilt: 7.23,
      eccentricity: 0.7512,
      color: 0x999aaa,
    },
  ],
};

export const STAR_DATA = {
  siriusA: {
    name: 'Sirius A',
    nameKo: '\uc2dc\ub9ac\uc6b0\uc2a4 A',
    emoji: '⭐',
    factsKo: [
      '밤하늘에서 가장 밝게 보이는 별이에요.',
      '우리 태양보다 하얗고 뜨거워요.',
      '큰개자리에서 찾을 수 있어요.',
    ],
    sizeComparisonKo: '시리우스 A는 우리 태양보다 1.7배쯤 큰 별이에요!',
    type: 'Main Sequence (A1V)',
    typeKo: '\uc8fc\uacc4\uc5f4\uc131 (A1V)',
    radius: 1189000,
    radiusSolar: 1.711,
    displayRadius: 70,
    distance: 8.6,
    distanceUnit: 'ly',
    distanceDisplay: 1500,
    azimuth: 0,
    elevation: 0.2,
    mass: 2.063,
    massUnit: 'M\u2609',
    luminosity: 25.4,
    luminosityUnit: 'L\u2609',
    surfaceTemp: 9940,
    color: 0xc8d8ff,
    emissive: 0x8098ff,
    constellation: 'Canis Major',
    constellationKo: '\ud070\uac1c\uc790\ub9ac',
    apparentMagnitude: -1.46,
    absoluteMagnitude: 1.42,
  },
  siriusB: {
    name: 'Sirius B',
    nameKo: '\uc2dc\ub9ac\uc6b0\uc2a4 B',
    emoji: '✨',
    factsKo: [
      '시리우스 A 옆에 있는 작은 별이에요.',
      '아주 작지만 무척 무거운 별이에요.',
      '너무 작아서 눈으로는 안 보여요.',
    ],
    sizeComparisonKo: '시리우스 B는 지구와 크기가 거의 같아요!',
    type: 'White Dwarf (DA2)',
    typeKo: '\ubc31\uc0c9\uc654\uc131 (DA2)',
    radius: 5800,
    radiusSolar: 0.0084,
    displayRadius: 8,
    distance: 8.6,
    distanceUnit: 'ly',
    distanceDisplay: 1540,
    azimuth: 0.15,
    elevation: 0.2,
    mass: 1.018,
    massUnit: 'M\u2609',
    luminosity: 0.056,
    luminosityUnit: 'L\u2609',
    surfaceTemp: 25200,
    color: 0xe0e8ff,
    emissive: 0xa0b0ff,
    constellation: 'Canis Major',
    constellationKo: '\ud070\uac1c\uc790\ub9ac',
    apparentMagnitude: 8.44,
    absoluteMagnitude: 11.18,
  },
  betelgeuse: {
    name: 'Betelgeuse',
    nameKo: '\ubca0\ud154\uac8c\uc6b0\uc2a4',
    emoji: '🟥',
    factsKo: [
      '오리온자리 어깨에서 붉게 빛나요.',
      '아주 크고 붉은 별이에요.',
      '우리 태양보다 훨씬 시원한 별이에요.',
    ],
    sizeComparisonKo: '태양 900개를 나란히 놓으면 베텔게우스 폭이에요!',
    type: 'Red Supergiant (M1-M2 Ia-ab)',
    typeKo: '\uc801\uc0c9\ucd08\uac70\uc131 (M1-M2 Ia-ab)',
    radius: 617100000,
    radiusSolar: 887,
    displayRadius: 180,
    distance: 700,
    distanceUnit: 'ly',
    distanceDisplay: 2500,
    azimuth: 2.5,
    elevation: -0.1,
    mass: 16.5,
    massUnit: 'M\u2609',
    luminosity: 126000,
    luminosityUnit: 'L\u2609',
    surfaceTemp: 3600,
    color: 0xff6633,
    emissive: 0xcc3300,
    constellation: 'Orion',
    constellationKo: '\uc624\ub9ac\uc628\uc790\ub9ac',
    apparentMagnitude: 0.5,
    absoluteMagnitude: -5.85,
  },
  stephenson2_18: {
    name: 'Stephenson 2-18',
    nameKo: '\uc2a4\ud2f0\ube10\uc2a8 2-18',
    emoji: '🌟',
    factsKo: [
      '지금까지 찾은 가장 큰 별 중 하나예요.',
      '방패자리 쪽 아주 먼 곳에 있어요.',
      '너무 멀어서 눈으로는 안 보여요.',
    ],
    sizeComparisonKo: '태양 2000개를 나란히 놓아야 이 별 폭이에요!',
    type: 'Red Supergiant (M6)',
    typeKo: '\uc801\uc0c9\ucd08\uac70\uc131 (M6)',
    radius: 1494360000,
    radiusSolar: 2150,
    displayRadius: 300,
    distance: 18900,
    distanceUnit: 'ly',
    distanceDisplay: 3500,
    azimuth: 4.5,
    elevation: 0.3,
    mass: 12,
    massUnit: 'M\u2609',
    luminosity: 440000,
    luminosityUnit: 'L\u2609',
    surfaceTemp: 3200,
    color: 0xee4422,
    emissive: 0xbb2200,
    constellation: 'Scutum',
    constellationKo: '\ubc29\ud328\uc790\ub9ac',
    apparentMagnitude: 15.26,
    absoluteMagnitude: -7.66,
  },
};
